# .goreleaser.yaml
builds:
  - env:
    - CGO_ENABLED=0
    binary: unpoller
    goarm:
      - 6
      - 7
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: 386
      - goarm: mips64
      - gomips: hardfloat
      - goamd64: v4
      - goos: freebsd
        goarch: 386
dockers:
  - # amd64
    image_templates:
      - "ghcr.io/unpoller/unpoller:latest-amd64"
      - "ghcr.io/unpoller/unpoller:{{ .Tag }}-amd64"
      - "ghcr.io/unpoller/unpoller:v{{ .Major }}-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.documentation='https://unpoller.com/docs/install/docker'"
      - "--label=org.opencontainers.image.description='Telemetry and Observability for your UniFi Network'"
      - "--label=org.opencontainers.image.url='https://unpoller.com'"
      - "--label=org.opencontainers.image.source='https://github.com/unpoller/unpoller'"
      - "--label=org.opencontainers.image.vendor=unpoller"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--platform=linux/amd64"
    push_flags:
      - --tls-verify=false
  - # arm64
    image_templates:
      - "ghcr.io/unpoller/unpoller:latest-arm64v8"
      - "ghcr.io/unpoller/unpoller:{{ .Tag }}-arm64v8"
      - "ghcr.io/unpoller/unpoller:v{{ .Major }}-arm64v8"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.documentation='https://unpoller.com/docs/install/docker'"
      - "--label=org.opencontainers.image.description='Telemetry and Observability for your UniFi Network'"
      - "--label=org.opencontainers.image.url='https://unpoller.com'"
      - "--label=org.opencontainers.image.source='https://github.com/unpoller/unpoller'"
      - "--label=org.opencontainers.image.vendor=unpoller"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--platform=linux/arm64"
    push_flags:
      - --tls-verify=false
  - # armv7
    image_templates:
      - "ghcr.io/unpoller/unpoller:latest-armv7"
      - "ghcr.io/unpoller/unpoller:{{ .Tag }}-armv7"
      - "ghcr.io/unpoller/unpoller:v{{ .Major }}-armv7"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.documentation='https://unpoller.com/docs/install/docker'"
      - "--label=org.opencontainers.image.description='Telemetry and Observability for your UniFi Network'"
      - "--label=org.opencontainers.image.url='https://unpoller.com'"
      - "--label=org.opencontainers.image.source='https://github.com/unpoller/unpoller'"
      - "--label=org.opencontainers.image.vendor=unpoller"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--platform=linux/arm/v7"
    push_flags:
      - --tls-verify=false
docker_manifests:
  - name_template: ghcr.io/unpoller/unpoller:{{ .Version }}
    image_templates:
      - ghcr.io/unpoller/unpoller:{{ .Version }}-amd64
      - ghcr.io/unpoller/unpoller:{{ .Version }}-arm64v8
      - ghcr.io/unpoller/unpoller:{{ .Version }}-armv7

nfpms:
  -
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Tux

    vendor: unpoller
    homepage: https://unpoller.com/
    maintainer: unpoller.com
    description: Telemetry and Observability for your UniFi Network
    license: MIT
    formats:
      - apk
      - deb
      - rpm
      - termux.deb # Since GoReleaser v1.11.
    bindir: /usr/bin
    version_metadata: git
    section: default
    priority: extra

    # Contents to add to the package.
    # GoReleaser will automatically add the binaries.
    contents:
      - dst: /etc/unpoller
        type: dir
        file_info:
          mode: 0700

      # Example config files
      - src: examples/up.conf.example
        dst: /etc/unpoller/up.conf.example
        type: config
      - src: examples/up.json.example
        dst: /etc/unpoller/up.json.example
        type: config
      - src: examples/up.yaml.example
        dst: /etc/unpoller/up.yaml.example
        type: config
universal_binaries:
  - replace: true
