language: go
# so we can build an osx package.
os: osx
addons:
  homebrew:
    packages:
    - rpm
    - gnu-tar
go:
- 1.12.x
before_install:
- mkdir -p $GOPATH/bin
  # Download the `dep` binary to bin folder in $GOPATH
- curl -sLo $GOPATH/bin/dep https://github.com/golang/dep/releases/download/v0.5.3/dep-darwin-amd64
- chmod +x $GOPATH/bin/dep
  # download super-linter: golangci-lint
- curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
#- curl -sL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
install:
- dep ensure
- rvm $brew_ruby do gem install --no-document fpm
script:
- rvm $brew_ruby do make release
# get deploy key for golift/homebrew-mugs.
after_success:
  - |
      declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
      echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      openssl aes-256-cbc -K $encrypted_9f3147001275_key -iv $encrypted_9f3147001275_iv -in ".travis/github_deploy_key.enc" -out "$SSH_FILE" -d
      chmod 600 "$SSH_FILE" \
        && printf "%s\n" \
          "Host github.com" \
          "  IdentityFile $SSH_FILE" \
          "  StrictHostKeyChecking no" \
          "  LogLevel ERROR" >> ~/.ssh/config
deploy:
  - provider: releases
    api_key:
      secure: GsvW0m+EnRELQMk8DjH63VXinqbwse4FJ4vNUslOE6CZ8PBXPrH0ZgaI7ic/uxRtm7CYj0sir4CZq62W5l6uhoXCCQfjOnmJspqnQcrFZ1xRdWktsNXaRwM6hlzaUThsJ/1PD9Psc66uKXBYTg0IlUz0yjZAZk7tCUE4libuj41z40ZKxUcbfcNvH4Njc9IpNB4QSA3ss+a9/6ZwBz4tHVamsGIrzaE0Zf99ItNBYvaOwhM2rC/NWIsFmwt8w4rIA2NIrkZgMDV+Z2Niqh4JRLAWCQNx/RjC5U52lG2yhqivUC3TromZ+q4O4alUltsyIzF2nVanLWgJmbeFo8uXT5A+gd3ovSkFLU9medXd9i4kap7kN/o5m9p5QZvrdEYHEmIU4ml5rjT2EQQVy5CtSmpiRAbhpEJIvA1wDtRq8rdz8IVfJXkHNjg2XdouNmMMWqa3OkEPw21+uxsqv4LscW/6ZjsavzL5SSdnBRU9n79EfGJE/tJLKiNumah/vLuJ5buNhgqmCdtX/Tg+DhQS1BOyYg4l4L8s9IIKZgFRwrOPsZnA/KsrWg4ZsjJ87cqKCaT/qs2EJx5odZcZWJYLBngeO8Tc6cQtLgJdieY2oEKo51Agq4rgikZDt21m6TY9/R5lPN0piwdpy3ZGKfv1ijXx74raMT03qskputzMCvc=
    overwrite: true
    skip_cleanup: true
    file_glob: true
    file: release/*
    on:
      repo: davidnewhall/unifi-poller
      tags: true
  - provider: script
    script: scripts/formula-deploy.sh
    on:
      tags: true
      repo: davidnewhall/unifi-poller
env:
  global:
    - GH_USER_NAME=unifi-auto-releaser
    - GH_USER_EMAIL=unifi@auto.releaser
